weapon:
  aliyun:
    ons:
      producer:
        default:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
app:
  schedule:
    builder:
      aspectLogFile: ./logs/aspect/job_builder.log
    scheduler:
      aspectLogFile: ./logs/aspect/scheduler.log