spring:
  application:
    name: darwin-scheduler
  profiles:
    active: @profileActive@
  config:
    import:
      - classpath:application-service.yml
      - classpath:application-service-@profileActive@.yml
      - classpath:application-queue.yml
      - classpath:application-queue-@profileActive@.yml
      - classpath:application-log.yml
      - classpath:application-log-@profileActive@.yml

app:
  schedule:
    maxOverflowTimeMs: 7200000
    planExecuteIntervalMs: 60000
    queueScheduleIntervalMs: 10000