weapon:
  aliyun:
    ons:
      producer:
        default:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
app:
  scheduler:
    job-builder:
      aspectLogFile: ./logs/aspect/job_builder.log
    url-scheduler:
      aspectLogFile: ./logs/aspect/scheduler.log