spring:
  application:
    name: darwin-scheduler
  profiles:
    active: @profileActive@
    include: service,service-@profileActive@,queue,queue-@profileActive@,log,log-@profileActive@

app:
  schedule:
    maxOverflowTimeMs: 7200000
    planExecuteIntervalMs: 60000
    queueScheduleIntervalMs: 10000