weapon:
  common:
    kafka:
      auth:
        security-protocol: SASL_PLAINTEXT
        sasl-mechanism: SCRAM-SHA-256
        sasl-jaas-config: ${weapon/kafka/jaas-config}
      consumer:
        servers: localhost:9092
        group-id: GID-TEST-DARWIN-FETCH-URL
        name: url_consumer
        processor-name: URLReceiver
        consumeThreadNum: 5
        topics:
          - TEST-DARWIN-FETCH-URL