app:
  executor:
    scheduler:
      max-overflow-time-ms: 7200000
      plan-scheduler-execute-interval-ms: 60000
      url-scheduler-execute-interval-ms: 10000
      proxy-refresher-execute-time-interval-ms: 300000
    monitor:
      multi-queue-execute-time-interval-ms: 600000
      multi-queue-expired-time-interval-ms: 600000
      concurrent-execute-time-interval-ms: 60000
      concurrent-expired-time-interval-ms: 300000
      proxy-execute-time-interval-ms: 30000