spring:
  application:
    name: darwin-spider
  profiles:
    active: @profileActive@
    include: service,service-@profileActive@,queue,queue-@profileActive@,log,log-@profileActive@

app:
  spider:
    reuseExpiredTimeMs: 86400000
    connectTimeoutSeconds: 5
    readTimeoutSeconds: 10
    keepAliveMinutes: 3
    maxIdleConnections: 100
    retryCnt: 3