spring:
  application:
    name: darwin-spider
  config:
    activate:
      on-profile: @profileActive@
    import:
      - classpath:application-service.yml
      - classpath:application-service-@profileActive@.yml
      - classpath:application-queue.yml
      - classpath:application-queue-@profileActive@.yml
      - classpath:application-log.yml
      - classpath:application-log-@profileActive@.yml

app:
  spider:
    reuseExpiredTimeMs: 86400000
    connectTimeoutSeconds: 5
    readTimeoutSeconds: 10
    keepAliveMinutes: 3
    maxIdleConnections: 100
    retryCnt: 3