weapon:
  aliyun:
    ons:
      producer:
        default:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
      consumer:
        html:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: xxx
          consumeThreadNum: 20
          subscribes:
            - topic: xxx
              tags: 0||1
              listener-name: urlReceiver
        resource:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: xxx
          consumeThreadNum: 20
          subscribes:
            - topic: xxx
              tags: 2||3
              listener-name: urlReceiver
app:
  spider:
    content-region: cn-hangzhou
    content-bucket: default-crawler-file
    content-directory: darwin
    job-topic: xxx
    record-topic: xxx
    temp-directory: ./spider/temp/
    aspect-log-file: ./log/aspect/spider.log