weapon:
  common:
    etcd:
      client:
        username: root
        password: xmjjyhy28p
        endpoints:
          - http://127.0.0.1:2379
    kafka:
      consumer:
        many:
          html:
            servers: localhost:9092
            group-id: GID_TEST_DARWIN_FETCH_HTML
            name: html_consumer
            processor-name: htmlURLReceiver
            consumeThreadNum: 2
            topics:
              - TEST_DARWIN_FETCH_URL
            auth-config:
              security-protocol: SASL_PLAINTEXT
              sasl-mechanism: PLAIN
              sasl-jaas-config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-123456";'
          resource:
            servers: localhost:9092
            group-id: GID_TEST_DARWIN_FETCH_RESOURCE
            name: resource_consumer
            processor-name: resourceURLReceiver
            consumeThreadNum: 2
            topics:
              - TEST_DARWIN_FETCH_URL
            auth-config:
              security-protocol: SASL_PLAINTEXT
              sasl-mechanism: PLAIN
              sasl-jaas-config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-123456";'
  aliyun:
    oss:
      client:
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
        socket-timeout-ms: 3000
        connection-timeout-ms: 3000
        retry-cnt: 2
app:
  spider:
    content-region: cn-hangzhou
    content-bucket: darwin-spider
    content-directory: content
    temp-directory: ./temp/