weapon:
  aliyun:
    oss:
      client-map:
        default:
          endpoint: https://oss-cn-hangzhou.aliyuncs.com
          socket-timeout-ms: 3000
          connection-timeout-ms: 3000
          retry-cnt: 3
    ons:
      producer-map:
        default:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
      consumer-map:
        html:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: GID_TEST_DARWIN_FETCH_HTML
          consumeThreadNum: 2
          subscribes:
            - topic: TEST_DARWIN_FETCH_URL
              tags: 1||2
              listener-name: urlReceiver
        resource:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: GID_TEST_DARWIN_FETCH_RESOURCE
          consumeThreadNum: 2
          subscribes:
            - topic: TEST_DARWIN_FETCH_URL
              tags: 3||4
              listener-name: urlReceiver
app:
  spider:
    content-region: cn-hangzhou
    content-bucket: default-crawler-file
    content-directory: darwin
    temp-directory: ./spider/temp/