weapon:
  aliyun:
    oss:
      client:
        default:
          endpoint: https://oss-cn-hangzhou.aliyuncs.com
          socket-timeout-ms: 3000
          connection-timeout-ms: 3000
          retry-cnt: 3
    ons:
      producer:
        default:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
      consumer:
        html:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: GID_TEST_DARWIN_FETCH_HTML
          consumeThreadNum: 2
          subscribes:
            - topic: TEST_DARWIN_FETCH_URL
              tags: 0||1
              listener-name: urlReceiver
        resource:
          serverURL: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          consumeId: GID_TEST_DARWIN_FETCH_RESOURCE
          consumeThreadNum: 2
          subscribes:
            - topic: TEST_DARWIN_FETCH_URL
              tags: 2||3
              listener-name: urlReceiver
app:
  spider:
    content-region: cn-hangzhou
    content-bucket: default-crawler-file
    content-directory: darwin
    record-topic: TEST_DARWIN_DISPATCH_RECORD
    temp-directory: ./spider/temp/