app:
  spider:
    max-content-length: 10485760
    max-repeat-fetch-time-interval-ms: 7200000
    connect-timeout-seconds: 5
    read-timeout-seconds: 10
    keep-alive-minutes: 3
    max-idle-connections: 100
    retry-cnt: 3
    max-depth: 3
    max-browser-sessions: 10
    browser-execute-path: /Users/frankcl/Downloads/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing