weapon:
  common:
    redis:
      client:
        mode: SINGLE
        connection-pool-size: 200

app:
  queue:
    concurrencyQueue:
      max-queue-capacity: 5000
      danger-memory-used-ratio: 0.95
      waring-memory-used-ratio: 0.90
    concurrencyControl:
      concurrent-connection-ttl-second: 3600
