weapon:
  common:
    redis:
      client:
        default:
          mode: SINGLE
          connection-pool-size: 200

app:
  queue:
    multi:
      max-used-memory-ratio: 0.95
      monitor-check-time-interval-ms: 3600000
      expired-time-interval-ms: 86400000
    concurrent:
      max-concurrent-connection-num: 50
      max-update-expired-time-interval-ms: 600000
      concurrent-connection-ttl-second: 3600