spring:
  application:
    name: darwin-web
  profiles:
    active: @profileActive@
  config:
    import:
      - classpath:application-executor.yml
      - classpath:application-executor-@profileActive@.yml
      - classpath:application-service.yml
      - classpath:application-service-@profileActive@.yml
      - classpath:application-queue.yml
      - classpath:application-queue-@profileActive@.yml
      - classpath:application-log.yml
      - classpath:application-log-@profileActive@.yml

server:
  port: 10001
  insecure-port: 10000
  ssl:
    key-store: classpath:manong.xin.jks
    key-store-type: jks
    key-password: xmjjyhy28p
  jetty:
    threads:
      acceptors: 2
      selectors: 4
      min: 8
      max: 200
    max-http-form-post-size: 1048576
  address: 0.0.0.0

app:
  web:
    name: darwin-web
    connectionExpiredTimeMs: 300000
    ignore-check-permission: false