hylian:
  client:
    appId: f733a689783eee56ad79886de1012699
    appSecret: oSUf9lwQ
    serverURL: https://hylian.manong.xin/
  filter:
    guard:
      excludePatterns:
        - api/health/*
        - api/app/get
        - api/app/search
        - api/app_user/getAppUsers
        - api/user/allUsers
        - api/plan/get
        - api/plan/search
        - api/job/get
        - api/job/progress
        - api/job/bucketCountGroupByStatus
        - api/job/search
        - /api/rule/get
        - /api/rule/planRules
        - /api/rule/history/search
        - /api/rule/history/get
        - /api/seed/get
        - /api/seed/search
        - /api/url/get
        - /api/url/preview
        - /api/url/previewHTML
        - /api/url/search
        - /api/executor/getList
        - /api/proxy/search
        - /api/proxy/get
        - favicon.ico

app:
  web:
    aspect-log-file: ./log/aspect/web.log