hylian:
  client:
    appId: f733a689783eee56ad79886de1012699
    appSecret: oSUf9lwQ
    serverURL: https://hylian.manong.xin/
  filter:
    guard:
      excludePatterns:
        - api/health/*
        - api/app/get
        - api/app/search
        - api/app_user/getAppUsers
        - api/user/allUsers
        - api/plan/get
        - api/plan/search
        - api/job/get
        - api/job/progress
        - api/job/successRate
        - api/job/search
        - /api/rule/get
        - /api/rule/planRules
        - /api/rule/history/search
        - /api/rule/history/get
        - /api/rule/getTemplate
        - /api/seed/get
        - /api/seed/search
        - /api/url/get
        - /api/url/preview
        - /api/url/previewHTML
        - /api/url/previewStream
        - /api/url/search
        - /api/runner/getList
        - /api/runner/isRunning
        - /api/runner/messageCount
        - /api/proxy/search
        - /api/concurrency/getConcurrencyUnit
        - /api/concurrency/getConcurrencyQueueWait
        - /api/concurrency/waitConcurrencyUnits
        - /api/concurrency/getDefaultCrawlDelay
        - /api/concurrency/getCrawlDelayMap
        - /api/concurrency/getDefaultConcurrency
        - /api/concurrency/getConcurrencyConnectionMap
        - /api/dashboard/fetchCountTrend
        - /api/dashboard/getQueueMemory
        - /api/dashboard/getQueueWait
        - /api/dashboard/queueWaitPriority
        - /api/dashboard/getDownAnalysis
        - /api/dashboard/getFetchAnalysis
        - /api/dashboard/statusGroupCount
        - /api/dashboard/contentGroupCount
        - /api/dashboard/hostFetchCount
        - favicon.ico