spring:
  application:
    name: darwin-web
  profiles:
    active: @profileActive@
    include: service,service-@profileActive@,queue,queue-@profileActive@,log,log-@profileActive@
  server: 8080

app:
  web:
    name: darwin-web
    connectionExpiredTimeMs: 300000