spring:
  application:
    name: darwin-web
  config:
    activate:
      on-profile: @profileActive@
    import:
      - classpath:application-service.yml
      - classpath:application-service-@profileActive@.yml
      - classpath:application-queue.yml
      - classpath:application-queue-@profileActive@.yml
      - classpath:application-log.yml
      - classpath:application-log-@profileActive@.yml

server:
  port: 8080

app:
  web:
    name: darwin-web
    connectionExpiredTimeMs: 300000