hylian:
  client:
    appId: f733a689783eee56ad79886de1012699
    appSecret: oSUf9lwQ
    serverURL: https://hylian.manong.xin/
  filter:
    guard:
      excludePatterns:
        - api/health/*
        - api/app/get
        - api/app/search
        - api/app_user/getAppUsers
        - api/user/allUsers
        - api/plan/get
        - api/plan/search
        - api/job/get
        - api/job/progress
        - api/job/countGroupByStatus
        - api/job/countGroupByCategory
        - api/job/search
        - /api/rule/get
        - /api/rule/planRules
        - /api/rule/history/search
        - /api/rule/history/get
        - /api/rule/getTemplate
        - /api/seed/get
        - /api/seed/search
        - /api/url/get
        - /api/url/preview
        - /api/url/previewHTML
        - /api/url/previewPDF
        - /api/url/search
        - /api/runner/getList
        - /api/runner/isRunning
        - /api/runner/messageCount
        - /api/proxy/search
        - /api/proxy/get
        - /api/concurrency/getConcurrencyUnit
        - /api/concurrency/topConcurrencyUnits
        - /api/concurrency/concurrencyQueueMemory
        - /api/concurrency/getDefaultConcurrency
        - /api/concurrency/getConcurrencyConnectionMap
        - /api/dashboard/totalTrend
        - /api/dashboard/statusTrend
        - /api/dashboard/contentTrend
        - /api/dashboard/averageContentLength
        - /api/dashboard/percentage
        - /api/dashboard/topHosts
        - favicon.ico