spring:
  application:
    name: darwin-web-server
  profiles:
    active: @profileActive@
    include: service,service-@profileActive@,queue,queue-@profileActive@
  server: 8080

app:
  web:
    name: darwin-web-server