hylian:
  client:
    appId: darwin
    appSecret: 123456
    serverURL: http://192.168.3.43:8080/
  filter:
    guard:
      excludePatterns:
        - api/health/*
        - favicon.ico

app:
  web:
    ignore-check-permission: true
    aspect-log-file: ./log/aspect/web.log